# Generated by Django 4.2.3 on 2023-07-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigation',
            name='bannerimage',
            field=models.ImageField(null=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='navigation',
            name='icon_image',
            field=models.ImageField(null=True, upload_to='about/'),
        ),
    ]
