# Generated by Django 4.2.3 on 2023-08-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_remove_globalsettings_image_globalsettings_brochure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigation',
            name='banner_image1',
        ),
        migrations.AddField(
            model_name='navigation',
            name='brochure',
            field=models.FileField(null=True, upload_to='brochure/'),
        ),
    ]
