# Generated by Django 4.2.3 on 2023-08-03 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0012_alter_navigation_page_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigation',
            name='long_desc',
        ),
        migrations.RemoveField(
            model_name='navigation',
            name='title1',
        ),
    ]
