# Generated by Django 4.2.3 on 2023-08-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0014_alter_navigation_page_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='back_image',
            field=models.ImageField(null=True, upload_to='Global/'),
        ),
    ]
