# Generated by Django 4.2.3 on 2023-08-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0017_alter_navigation_page_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='SiteContact',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='Sitefacebooklink',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='Siteinstagram',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='Sitelicence',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='Sitelinkdinlink',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='Sitetwitterlink',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='Siteyoutubelink',
            field=models.CharField(max_length=300),
        ),
    ]
